CREATE TABLE USER(USERID VARCHAR(20), PASSWORD_HASH VARCHAR(100) NOT NULL, NAME VARCHAR(100) NOT NULL, ROLE VARCHAR(20) NOT NULL, PHONE VARCHAR(20), EMAIL VARCHAR(100), ISACTIVE BIT, PRIMARY KEY (USERID));

CREATE TABLE RESERVATION(ID VARCHAR(36), USERID VARCHAR(20) NOT NULL, COURT_ID VARCHAR(100) NOT NULL, DATE DATE NOT NULL, START_AT INT NOT NULL, HOURS INT NOT NULL, TIMESTAMP TIMESTAMP NOT NULL, COMMENT VARCHAR(1000), PRIMARY KEY (ID));

CREATE TABLE RESERVATION_OPEN(DATE DATE, OPEN_AT TIME, PRIMARY KEY (DATE));